theme: jekyll-theme-tactile
collections:
  posts:
    output          : true

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false